In [1]:
import pandas as pd
import seaborn as sns

In [2]:
insurance_data = pd.read_csv("insurance.csv")

In [8]:
X = insurance_data.drop(columns=["charges", "region"])
Y = insurance_data["charges"]

X["sex"] = X["sex"].map({"female" : 1, "male" : 0})
X["smoker"] = X["smoker"].map({"yes" : 1, "no" : 0})

In [9]:
X.head()

   age  sex     bmi  children  smoker
0   19    1  27.900         0       1
1   18    0  33.770         1       0
2   28    0  33.000         3       0
3   33    0  22.705         0       0
4   32    0  28.880         0       0

In [10]:
#Train Test Split
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, Y,
    test_size=0.2,   # 20% test data
    random_state=42  # for reproducibility
)

In [14]:
#Train Model
from sklearn.linear_model import LinearRegression

In [15]:
# Create model
model = LinearRegression()

# Train model
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

In [20]:
#Evaluate
from sklearn.metrics import r2_score

In [23]:
r2 = r2_score(y_test, y_pred)

n = len(y_test)      # number of samples or can use X_test.shape[0] both same
p = X_test.shape[1]  # number of features

adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

print("R2:", r2)
print("Adjusted R2:", adj_r2)

R2: 0.7811302113434095
Adjusted R2: 0.7769533069797342

In [55]:
#Practice Problem House Price Prediction
house_price_data = pd.read_csv("HousePricePrediction.csv")

In [56]:
#Cleaning
X = house_price_data.drop(columns=["Id","SalePrice"])
Y = house_price_data["SalePrice"]

X.isnull().sum()
# Y.isnull().sum()

MSSubClass      0
MSZoning        4
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     1
BsmtFinSF2      1
TotalBsmtSF     1
dtype: int64

In [57]:
# If missing:
# Numeric → fill with mean
# Eg : df.fillna(df.mean(numeric_only=True), inplace=True)

X.fillna(X.mean(numeric_only=True), inplace=True)
Y.fillna(Y.mean(numeric_only=True), inplace=True)

# Categorical → fill with most common
# Eg : df.fillna(df.mode().iloc[0], inplace=True)

X.fillna(X.mode().iloc[0], inplace=True)

X.head()
# X.isnull().sum()

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0

In [58]:
# Convert text → numbers
# Machine learning only understands numbers.
# df = pd.get_dummies(df)
# dtype=
# pd.get_dummies(df, dtype=int)
# Ensures output is integer (0/1 instead of True/False)

# X = pd.get_dummies(X, dtype=int)
X = pd.get_dummies(X, columns=["MSZoning", "LotConfig", "BldgType", "Exterior1st"], dtype=int)

In [60]:
X_train, X_test, y_train, y_test = train_test_split(
    X, Y,
    test_size=0.2,   # 20% test data
    random_state=42  # for reproducibility
)
# Create model
model = LinearRegression()

# Train model
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
r2 = r2_score(y_test, y_pred)

n = len(y_test)      # number of samples or can use X_test.shape[0] both same
p = X_test.shape[1]  # number of features

adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

print("R2:", r2)
print("Adjusted R2:", adj_r2)

R2: 0.3360214016132699
Adjusted R2: 0.29102651490940723